console.log('hello, world');
const title = document.querySelector('h1');
console.log(title);
console.dir(title);
const textContent = document.querySelector('#explanation');
console.log(textContent);
console.dir(textContent);
const selector = document.querySelector('.hint');
console.log(selector);
console.dir(selector);
const selectorAll = document.querySelectorAll('example-link');
console.log(selectorAll);
